# Generated by Django 4.2.3 on 2023-07-21 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_sales_value_products_price_sales_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='quantidade',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='quantidade',
            new_name='amount',
        ),
    ]
