# Generated by Django 4.2.3 on 2023-07-23 16:27

from django.db import migrations, models


def popular_tabela(apps, schema_editor):
    Products = apps.get_model('clients', 'Products')
    # Substitua 'myapp' pelo nome do aplicativo Django que contém o modelo 'Products'

    produtos_iniciais = [
        {'name': 'Camiseta', 'amount': 10, 'price': 25.99},
        {'name': 'Caderno', 'amount': 20, 'price': 15.49},
        {'name': 'Mochila', 'amount': 15, 'price': 50.99},
    ]

    for produto in produtos_iniciais:
        Products.objects.create(**produto)


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_rename_quantidade_products_amount_and_more'),
    ]

    operations = [
        migrations.RunPython(popular_tabela),
    ]
